### ISSUE TITLE
It cannot even register,its  always say that invalid details

### ISSUE THREAD

**Issue by ahmedyounas** [imrananwar706official/blood-donors-android-java#1]

**Comment by imrananwar706** [comment]
Can you show your database structure

**Comment by ahmedyounas** [comment]
Registration issue is resolve but my data can't search and store in
database can u please help me ? im new with firebase

**Comment by imrananwar706** [comment]
If you show your database structure then i can help you

Sent from Yahoo Mail on Android 
 
  On Mon, Feb 18, 2019 at 7:18 PM, Ahmed Younas<notifications@github.com> wrote:   Registration issue is resolve but my data can't search and store in
database can u please help me ? im new with firebase
